# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            josedlpozo
description:      'Adventures as an indie developer'
url:              https://josedlpozo.com
baseurl:          /

author:
  name:           'josedlpozo'
  url:            https://twitter.com/Josedlpozo

paginate:         5

plugins: [jekyll-paginate]